### ISSUE TITLE
Is there a public repo for azure cognitive search itself?

### ISSUE THREAD

**Issue by justinmchase** [microsoft/vscode-azurecognitivesearch#37]
I'm trying to figure out how to file some issues / feature requests and can't seem to find any sources of truth in either the Azure or Microsoft orgs.

**Comment by dereklegenzoff** [comment]
Hi @justinmchase - for feature requests, I'd recommend submitting them here: https://feedback.azure.com/d365community/forum/9325d19e-0225-ec11-b6e6-000d3a4f07b8

For issues, the correct spot depends a bit on what the issue is - if you have an issue with the product itself, i'd recommend submitting a support request. If it's a doc issue or an SDK issue, there are repos for those where you can file issues.

**Comment by justinmchase** [comment]
The main thing is getting an emulator for local development. But I have a few others as well. Thank you for the link.

**Comment by justinmchase** [comment]
@dereklegenzoff So that forum has 0 completed feedback items:
https://feedback.azure.com/d365community/forum/9325d19e-0225-ec11-b6e6-000d3a4f07b8

The top 100 or so are all from like 6+ years ago. This is a little scary. Can you ask the team to go through that and maybe respond to items and mark items as compelted if they were actually completed and maybe get an actual git repo up so people can see progress and share their product plan because honestly I'm a little scared now that this is abandonware after struggling to find any signs of life from the team.

**Comment by dereklegenzoff** [comment]
Hi @justinmchase - unfortunately we're not planning on creating an emulator for local development. We recommend using free services for scenarios like that.

And I certainly hear your feedback. Some of those stats are inaccurate because the feedback recently got migrated to a new site. I can promise you we do read the feedback although I admit, we haven't been great about keeping it updated.
